### ISSUE TITLE
Add button for optional JSON export

### ISSUE THREAD

**Issue by talves** [Kinark/netlify-config-builder#1]
@Kinark Igor, this is an **awesome** implementation of a configurator for `netlify-cms`. I put a JSON export in my currently deprecated configurator. 

Have to use JSON when using manual init of the cms. This is a feature request you can ignore, but thought I would bring it up, since you took the time to build this great looking tool. 😉

**Comment by Kinark** [comment]
Thank you for your kind words :D
I'll add a json export real soon!

**Comment by Kinark** [comment]
Added button to copy JSON to clipboard.
Thanks for your suggestion!
